version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    container_name: frontend
    restart: always
    ports:
      - 5173:5173
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    networks:
      - mynetwork

  backend:
    build: ./backend
    container_name: backend
    restart: always
    depends_on:
      - mysql
    # env_file:
    #   - ./config/.env   
    ports:
      - 8080:8080
    networks:
      - mynetwork

  mysql:
    image: mysql:latest
    container_name: db-dashboard
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db-dashboard
    volumes:
      - mysql_data:/var/lib/mysql
      # - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mynetwork

volumes:
  mysql_data:


networks:
  mynetwork:
    driver: bridge
